### ISSUE TITLE
Project looking for adoption

### ISSUE THREAD

**Issue by bragma** [bragma/winston-azure-application-insights#11]
I'm quite happy that this little piece of code is useful, but I have not much time to love it enough. I am looking for anyone proposing to adopt it. I feel bad seeing PRs and issues lingering for too long.
Thanks!

**Comment by willmorgan** [comment]
I can take it...

**Comment by willmorgan** [comment]
Feel free to email me to discuss - `jobs+github` at `<my github username>.co.uk`

**Comment by bragma** [comment]
@willmorgan no need, I've added you as collaborator to the project, but I am open to give up full ownership if needed.
