### ISSUE TITLE
this.client is undefined

### ISSUE THREAD

**Issue by joostpielage** [bragma/winston-azure-application-insights#15]
Hi @bragma ,

I would love top your app but I cannot get it right. This is the code I am having: 

const aiLogger = require('winston-azure-application-insights').AzureApplicationInsightsLogger;
const appInsights = require("applicationinsights");
appInsights.setup("64352017-d16d-49f4-9f61-a9b1188ef47f").start();
let client = appInsights.defaultClient;
let result = aiLogger({client : client});

Right now I seem to keep having this error: 

TypeError: Cannot set property 'client' of undefined
winston-azure-application-insights.js:61
    at AzureApplicationInsightsLogger

Any idea what is going wrong?

**Comment by willmorgan** [comment]
This is not a library defect; you are instantiating `winston-azure-application-insights` in an unusual way. 

If you wish to keep the code as-is, you are missing the `new` when creating `result`:

```js
const result = new aiLogger({ client });
```

Otherwise [please see the docs](https://github.com/bragma/winston-azure-application-insights#usage).

**Comment by joostpielage** [comment]
Thank you it is working now. Javascript.... Thank you for helping me out.
