### ISSUE TITLE
tracking exception tracks twice

### ISSUE THREAD

**Issue by jeffmcaffer** [bragma/winston-azure-application-insights#2]
Should there be a "return" on #[L124](https://github.com/bragma/winston-azure-application-insights/blob/master/lib/winston-azure-application-insights.js#L124)?  I'm seeing if errors as exceptions is on then we'll get a trackException (good) but then execution will continue and do a trackTrace (seems bad).

**Comment by bragma** [comment]
@jeffmcaffer can you please clone from devel branch and check if the issue is correctly fixed. It seems ok to me.
Thanks!

**Comment by jeffmcaffer** [comment]
sorry for the delay.  yeah, that cange looks good.  Thanks. Ship it!

**Comment by bragma** [comment]
Sorry for the late reply, I've merged all PRs in 1.1.1
