### ISSUE TITLE
NPM package registered to willmogan, not this specific repo

### ISSUE THREAD

**Issue by bpetty-interlace** [bragma/winston-azure-application-insights#20]
There are issues I would like to log but only this repo appears to be accepting Issues.
The repo registered with NPM does not... so you documentation in github will download a package from someone else's fork.

https://www.npmjs.com/package/winston-azure-application-insights%20winston-azure-application-insights

npm i winston-azure-application-insights   -- According to NPM will pull from @willmorgan 

@willmorgan Are you the new owner?  Do issues have to come through here?  Is the project still active?

**Comment by willmorgan** [comment]
I've enabled issue tracking on the fork; keen to know what issues you're having?
