### ISSUE TITLE
Incompatible with applicationinsights ^1.0.1: traces not sent to AI

### ISSUE THREAD

**Issue by willmorgan** [bragma/winston-azure-application-insights#8]
Hey @bragma, thanks for starting this library - it looks useful, and a colleague of mine has integrated it onto our project. We're currently using it inside a Function App deployment.

However, unfortunately, it seems that applicationinsights 1.x has broken this library's tracking. It also fails quietly:

```
ApplicationInsights:track() requires telemetry object and telemetryType to be specified. []
```

The AppInsights client trackTrace method now requires an object to be passed, rather than the old 3 parameter `(msg, level, meta)` signature:

* [new function signature](https://github.com/Microsoft/ApplicationInsights-node.js/blob/1.0.1/Library/TelemetryClient.ts#L50-L58)
* [new tests asserting this](https://github.com/Microsoft/ApplicationInsights-node.js/blob/1.0.1/Tests/Library/Client.tests.ts#L112-L130)

It also looks like `trackException` has changed, too.

The migration guide is here: https://github.com/Microsoft/ApplicationInsights-node.js/tree/1.0.1#migrating-from-versions-prior-to-022

**Comment by bragma** [comment]
Thanks, please see #11
